### ISSUE TITLE
yaml parsing issue

### ISSUE THREAD

**Issue by goshcharlotte** [minikomi/Bootstrap-Form-Builder#78]
Getting the following message when I try to run parse.rb - can you offer any suggestion as to why?

```
/Library/Ruby/Site/1.8/rubygems/core_ext/kernel_require.rb:55:in `gem_original_require': no such file to load -- json (LoadError)
    from /Library/Ruby/Site/1.8/rubygems/core_ext/kernel_require.rb:55:in `require'
    from parse.rb:4
```

I'm pretty new to this so I'm sorry if this is a stupid question.

**Comment by minikomi** [comment]
Try `gem install json` first
